www_dir = '/distr/www'

Vagrant.configure('2') do |config|
	config.vm.hostname = "docker.example.com"
	config.vm.box = "ubuntu/vivid64"
	config.vm.network :private_network, ip: "192.168.1.101"
	config.vm.provision :shell, path: 'set-docker-opts.sh'
	config.vm.provision :docker do |dock|
		dock.run 'webserver',
			image: 'nginx',
			args: '-p "8080:80" -p "8443:443" ' +
			"-v #{www_dir}/html:/usr/share/nginx/html:ro -v #{www_dir}/conf:/etc/nginx/conf.d:ro"
	end
end
